exports.pagMadres = [
    'https://en.wikipedia.org/wiki/Special:AllPages?from=a&to=&namespace=0', "https://en.wikipedia.org/wiki/Special:AllPages?from=Fa&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=gorilla&to=&namespace=0", 'https://en.wikipedia.org/wiki/Special:AllPages?from=her&to=&namespace=0', 'https://en.wikipedia.org/wiki/Special:AllPages?from=image&to=&namespace=0',
    "https://en.wikipedia.org/wiki/Special:AllPages?from=kend&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=leo&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=mes&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=nex&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=oscar&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=part&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=que&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=scar&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=tr&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=univ&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=vet&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=we&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=xip&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=you&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=ze&to=&namespace=0", "https://en.wikipedia.org/w/index.php?title=Special:AllPages&from=Zealandia+EcoSanctuary", "https://en.wikipedia.org/wiki/Special:AllPages?from=abi&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=bea&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=cana&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=der&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=fif&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=gui&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=hig&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=it&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=jennifer&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=kendall&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=kylie&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=low&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=mike&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=nig&to=&namespace=0", "https://en.wikipedia.org/wiki/Special:AllPages?from=oper&to=&namespace=0","https://en.wikipedia.org/wiki/Special:AllPages?from=pla&to=&namespace=0",
    "https://en.wikipedia.org/wiki/Special:AllPages?from=queen&to=&namespace=0","https://en.wikipedia.org/wiki/Special:AllPages?from=richard&to=&namespace=0","https://en.wikipedia.org/wiki/Special:AllPages?from=simon&to=&namespace=0",""
]